name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: deno install
      - run: deno fmt --check --unstable-component
      - run: deno task tauri build
